# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 65c2c1b85485249765ef14f7873d400a4c509bea6b66f0ca704fbf6d02cfd71f5b864dae4a09726f673be560f20e276d66b4e92682188ce1ae6d68fa8d33153a

test:
  secret_key_base: ebdd1ed2201510ba4e6ad646d328d4d5915e79281db989062f5895585d93538a94b6631f1c711ffe558640418985dd8d976f29e30ce1fa6a313aa1d39e6c7ded

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
